### ISSUE TITLE
304 报了个error

### ISSUE THREAD

**Issue by lxcuso4** [lvgithub/ctrip-apollo-client#1]
apollo-client: pollingNotification error:  Request failed with status code 304
304应该是使用缓存，但是却报了个error

**Comment by lvgithub** [comment]
304 是配置中心无更新,我处理下这个不进错误日志，下一版本发布。

非 200 的错误码，目前都统一打到错误日志。

**Comment by lvgithub** [comment]
fixed on [not log HTTP status 304 error](https://github.com/lvgithub/ctrip-apollo-client/pull/2)
