### ISSUE TITLE
apollo名称拼错了

### ISSUE THREAD

**Issue by cgx9** [lvgithub/ctrip-apollo-client#16]
https://github.com/lvgithub/ctrip-apollo-client/blob/7fe493f8673e6b1314940ff6f3536b70c4c290ab/typings/ctripApolloClient.d.ts#L17

CtripApplloClient -> CtripApolloClient

**Comment by lvgithub** [comment]
提一个PR哈

**Comment by lvgithub** [comment]
fixed
