### ISSUE TITLE
feat:支持通过AccessKey访问Apollo，获取配置，提升安全性。

### ISSUE THREAD

**Issue by qb2014** [lvgithub/ctrip-apollo-client#3]
我已经基于你的1.0.3的tag, 支持了通过AccessKey访问Apollo，能PR给你吗？

**Comment by lvgithub** [comment]
可以，谢谢

**Comment by qb2014** [comment]
> 可以，谢谢

但是推送不了我的分支，应该得设置一下仓库权限

**Comment by lvgithub** [comment]
加好了

**Comment by lvgithub** [comment]
npm 发布了 v1.0.5 版本
`npm i @lvgithub/ctrip-apollo-client`
