### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zxchcyc** [lvgithub/ctrip-apollo-client#8]
async polling () {
        let pollingCount = 1
        while (true) {
            this.info('polling count:', pollingCount++)
            try {
                await this.pollingNotification()
                await sleep(2000) // 这里不加会阻塞事件循环 长链接进不来 this.pollingNotification()加的已经被catch掉了
            } catch (error) {
                this.error('polling error:', error)
                await sleep(1000)
            }
        }
    }

**Comment by lvgithub** [comment]
fix on [pollingNotification throw error](https://github.com/lvgithub/ctrip-apollo-client/commit/e61cf489d9ad8699eb99d0dea5a2923ccd402283)

如果对你有用，欢迎点star

**Comment by zxchcyc** [comment]
好的
